- name: Copy wallpaper file
  copy: src=files/wallpaper.png dest=/home/yilisharcs/Pictures/wallpaper.png owner=yilisharcs group=yilisharcs mode=600

- name: Set GNOME Wallpaper
  become_user: yilisharcs
  dconf:
    key: "/org/gnome/desktop/background/picture-uri-dark"
    value: "'file:///home/yilisharcs/Pictures/wallpaper.png'"
    state: present

- name: Install GNOME-extension dependencies
  apt: name={{item}}
  with_items:
    - gir1.2-gtop-2.0        # Vitals
    - lm-sensors             # Vitals
