- name: Install from package manager
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - atool                          # compression and extraction tools
    - bat                            # better cat
    - bibata-cursor-theme
    - binaryen                       # wasm toolchain binaries
    - curl
    - dconf-editor
    - entr                           # file watcher
    - fd-find                        # better find
    - fzf                            # fuzzy finder
    - gh                             # github cli client
    - git
    - gimp                           # foss photoshop
    - gnome-shell-extension-manager
    - htop                           # cli system monitor
    - imagemagick
    - jq                             # yq but for json
    - lf                             # cli file explorer
    - make                           # makefiles
    - mesa-utils                     # gpu utils
    - ncdu                           # disk space checker
    - pass                           # cli password manager
    - pipx                           # python package manager
    - qbittorrent
    - ripgrep                        # better grep
    - rustup                         # rust toolchain manager
    - sccache                        # rust build cache tool
    - sqlite3
    - starship                       # shell prompt tool
    - stow                           # symlink manager
    - syncthing                      # peer-to-peer file sync
    - timeshift
    - tmux
    - tokei                          # loc counter
    - tree                           # recursive ls in tree format
    - wl-clipboard
    - yq                             # jq but for yaml
    - zoxide                         # better cd

- name: Install python packages
  pipx:
    name: "{{ item }}"
    state: present
  loop:
    - trash-cli
    - yt-dlp

- name: Install cargo packages
  become_user: yilisharcs
  cargo:
    name: "{{ item }}"
    state: present
    path: /home/yilisharcs/.cargo
  loop:
    - bacon
    - cargo-audit
    - cargo-auditable
    - cargo-binstall
    - cargo-modules
    - cargo-nextest
    - cargo-sweep
    - cargo-update
    - fnm                            # node version manager
    - rustlings
    - nu_plugin_inc
    - nu_plugin_polars
    - nu_plugin_gstat
    - nu_plugin_formats
    - nu_plugin_query
